import { createFileRoute } from "@tanstack/react-router";
import {
  Activity,
  AlertTriangle,
  ArrowRight,
  CheckCircle2,
  Database,
  FileSearch,
  Play,
  Server,
  ShieldCheck,
  Upload,
  XCircle,
} from "lucide-react";
import { useEffect, useState } from "react";

import {
  analyzeAll,
  checkBackend,
  uploadDataset,
  type UploadResult,
} from "@/lib/satsa-api";

export const Route = createFileRoute("/_workspace/dashboard")({
  head: () => ({
    meta: [
      { title: "Dashboard — SOC Strategy" },
      {
        name: "description",
        content: "SOC analyst analysis workspace.",
      },
    ],
  }),
  component: Dashboard,
});

type BackendState = "checking" | "online" | "offline";

function Dashboard() {
  const [backend, setBackend] = useState<BackendState>("checking");
  const [uploading, setUploading] = useState(false);
  const [analyzing, setAnalyzing] = useState(false);
  const [uploadResult, setUploadResult] = useState<UploadResult | null>(null);
  const [analysis, setAnalysis] = useState<Record<string, unknown> | null>(
    null,
  );
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    checkBackend()
      .then(() => setBackend("online"))
      .catch(() => setBackend("offline"));
  }, []);

  async function handleFiles(files: FileList | null) {
    if (!files?.length) return;

    setUploading(true);
    setError(null);

    try {
      const result = await uploadDataset(Array.from(files));
      setUploadResult(result);
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setUploading(false);
    }
  }

  async function runAnalysis() {
    setAnalyzing(true);
    setError(null);

    try {
      const result = await analyzeAll();
      setAnalysis(result);
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setAnalyzing(false);
    }
  }

  const datasetReady = uploadResult?.dataset_status === "ready";

  return (
    <div className="mx-auto max-w-7xl space-y-8">
      {/* Header */}
      <header>
        <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
          <div>
            <p className="eyebrow">SECURITY OPERATIONS WORKSPACE</p>

            <h1 className="mt-2 text-3xl font-semibold tracking-tight">
              SOC Analysis Command Center
            </h1>

            <p className="mt-2 max-w-2xl text-sm text-muted-foreground">
              Ingest your SOC dataset, validate the evidence structure, run
              analysis and investigate the findings generated by SAT-SA.
            </p>
          </div>

          <BackendIndicator state={backend} />
        </div>
      </header>

      {/* Error */}
      {error && (
        <div className="flex items-start gap-3 rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-sm">
          <XCircle className="mt-0.5 h-5 w-5 shrink-0" />
          <div>
            <p className="font-medium">Operation failed</p>
            <p className="mt-1 text-muted-foreground">{error}</p>
          </div>
        </div>
      )}

      {/* Top status */}
      <section className="grid gap-4 md:grid-cols-3">
        <StatusCard
          icon={Server}
          label="Backend"
          value={backend === "online" ? "Connected" : backend}
          good={backend === "online"}
        />

        <StatusCard
          icon={Database}
          label="Dataset"
          value={
            datasetReady
              ? `${uploadResult?.files_available ?? 0}/${uploadResult?.files_required ?? 0} files ready`
              : "Not loaded"
          }
          good={datasetReady}
        />

        <StatusCard
          icon={Activity}
          label="Analysis"
          value={analysis ? "Completed" : "Ready to run"}
          good={!!analysis}
        />
      </section>

      {/* Main workflow */}
      <section className="grid gap-6 xl:grid-cols-[1.4fr_0.8fr]">
        {/* Upload */}
        <div className="glass-panel rounded-2xl p-6">
          <div className="flex items-start justify-between gap-4">
            <div>
              <p className="eyebrow">01 · DATA INGESTION</p>
              <h2 className="mt-2 text-xl font-semibold">
                Load SOC evidence
              </h2>
              <p className="mt-1 text-sm text-muted-foreground">
                Upload the CSV collection used by the SAT-SA analysis engine.
              </p>
            </div>

            <Upload className="h-5 w-5 text-violet" />
          </div>

          <label className="mt-6 flex cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-border bg-background/30 px-6 py-12 text-center transition hover:border-violet/50 hover:bg-violet/5">
            <Upload className="h-8 w-8 text-muted-foreground" />

            <p className="mt-4 text-sm font-medium">
              {uploading ? "Uploading dataset..." : "Drop or select CSV files"}
            </p>

            <p className="mt-1 text-xs text-muted-foreground">
              cases · alerts · investigations · escalations · evidence ·
              events · assets
            </p>

            <input
              type="file"
              multiple
              accept=".csv"
              className="hidden"
              disabled={uploading}
              onChange={(e) => handleFiles(e.target.files)}
            />
          </label>

          {uploadResult && (
            <div className="mt-5 rounded-xl border border-border bg-background/30 p-4">
              <div className="flex items-center gap-2">
                {datasetReady ? (
                  <CheckCircle2 className="h-5 w-5 text-emerald-400" />
                ) : (
                  <AlertTriangle className="h-5 w-5 text-amber-400" />
                )}

                <span className="text-sm font-medium">
                  {uploadResult.message}
                </span>
              </div>

              <div className="mt-3 text-xs text-muted-foreground">
                Files available:{" "}
                <span className="text-foreground">
                  {uploadResult.files_available ?? 0}
                </span>{" "}
                / {uploadResult.files_required ?? 7}
              </div>

              {uploadResult.missing_files?.length ? (
                <div className="mt-3">
                  <p className="text-xs font-medium">Missing files</p>

                  <div className="mt-2 flex flex-wrap gap-2">
                    {uploadResult.missing_files.map((file) => (
                      <span
                        key={file}
                        className="rounded-md border border-border px-2 py-1 font-mono text-[10px]"
                      >
                        {file}
                      </span>
                    ))}
                  </div>
                </div>
              ) : null}
            </div>
          )}
        </div>

        {/* Analysis action */}
        <div className="glass-panel rounded-2xl p-6">
          <p className="eyebrow">02 · ANALYSIS ENGINE</p>

          <h2 className="mt-2 text-xl font-semibold">
            Turn telemetry into findings
          </h2>

          <p className="mt-2 text-sm leading-6 text-muted-foreground">
            Once the complete dataset is available, run the SAT-SA analysis
            engine to generate analytical findings.
          </p>

          <div className="mt-6 space-y-3">
            <PipelineItem
              icon={Database}
              text="Dataset validation"
              active={datasetReady}
            />

            <PipelineItem
              icon={Activity}
              text="Statistical analysis"
              active={!!analysis}
            />

            <PipelineItem
              icon={AlertTriangle}
              text="Anomaly detection"
              active={!!analysis}
            />

            <PipelineItem
              icon={FileSearch}
              text="Case-level investigation"
              active={!!analysis}
            />
          </div>

          <button
            onClick={runAnalysis}
            disabled={!datasetReady || analyzing}
            className="btn-cta mt-7 flex w-full items-center justify-center gap-2 rounded-full py-3 text-sm font-semibold disabled:cursor-not-allowed disabled:opacity-40"
          >
            <Play className="h-4 w-4" />

            {analyzing ? "Running SAT-SA analysis..." : "Run Full Analysis"}

            {!analyzing && <ArrowRight className="h-4 w-4" />}
          </button>

          {!datasetReady && (
            <p className="mt-3 text-center text-[11px] text-muted-foreground">
              Complete the dataset upload before running analysis.
            </p>
          )}
        </div>
      </section>

      {/* Results */}
      {analysis && (
        <section className="glass-panel rounded-2xl p-6">
          <div className="flex items-center gap-3">
            <ShieldCheck className="h-5 w-5 text-violet" />

            <div>
              <p className="eyebrow">03 · ANALYSIS RESULT</p>
              <h2 className="mt-1 text-xl font-semibold">
                SAT-SA findings generated
              </h2>
            </div>
          </div>

          <div className="mt-5 rounded-xl border border-border bg-background/40 p-4">
            <pre className="max-h-[500px] overflow-auto whitespace-pre-wrap break-words font-mono text-xs leading-5 text-muted-foreground">
              {JSON.stringify(analysis, null, 2)}
            </pre>
          </div>
        </section>
      )}

      {/* Workflow */}
      <section>
        <p className="eyebrow">ANALYST WORKFLOW</p>

        <div className="mt-4 grid gap-3 md:grid-cols-5">
          <WorkflowStep number="01" title="Upload" />
          <WorkflowStep number="02" title="Validate" />
          <WorkflowStep number="03" title="Analyze" />
          <WorkflowStep number="04" title="Investigate" />
          <WorkflowStep number="05" title="Report" />
        </div>
      </section>
    </div>
  );
}

function BackendIndicator({ state }: { state: BackendState }) {
  const online = state === "online";

  return (
    <div className="flex items-center gap-2 rounded-full border border-border bg-card/50 px-3 py-2 text-xs">
      <span
        className={`h-2 w-2 rounded-full ${
          online ? "bg-emerald-400" : "bg-amber-400"
        }`}
      />

      Backend {online ? "Connected" : "Checking"}
    </div>
  );
}

function StatusCard({
  icon: Icon,
  label,
  value,
  good,
}: {
  icon: typeof Server;
  label: string;
  value: string;
  good: boolean;
}) {
  return (
    <div className="glass-panel rounded-xl p-5">
      <div className="flex items-center justify-between">
        <p className="eyebrow">{label}</p>

        <Icon
          className={`h-4 w-4 ${
            good ? "text-emerald-400" : "text-muted-foreground"
          }`}
        />
      </div>

      <p className="mt-3 text-lg font-semibold">{value}</p>
    </div>
  );
}

function PipelineItem({
  icon: Icon,
  text,
  active,
}: {
  icon: typeof Database;
  text: string;
  active: boolean;
}) {
  return (
    <div className="flex items-center gap-3 rounded-lg border border-border bg-background/20 px-3 py-3">
      {active ? (
        <CheckCircle2 className="h-4 w-4 text-emerald-400" />
      ) : (
        <Icon className="h-4 w-4 text-muted-foreground" />
      )}

      <span className="text-sm">{text}</span>
    </div>
  );
}

function WorkflowStep({
  number,
  title,
}: {
  number: string;
  title: string;
}) {
  return (
    <div className="glass-panel rounded-xl p-4">
      <p className="font-mono text-[10px] text-violet">{number}</p>
      <p className="mt-2 text-sm font-medium">{title}</p>
    </div>
  );
}