/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteRouteImport } from './routes/_workspace/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WorkspaceAlertsRouteImport } from './routes/_workspace/alerts'
import { Route as WorkspaceAssetsRouteImport } from './routes/_workspace/assets'
import { Route as WorkspaceCaseAnalysisRouteImport } from './routes/_workspace/case-analysis'
import { Route as WorkspaceDashboardRouteImport } from './routes/_workspace/dashboard'
import { Route as WorkspaceDatasetAnalysisRouteImport } from './routes/_workspace/dataset-analysis'
import { Route as WorkspaceEvidenceRouteImport } from './routes/_workspace/evidence'
import { Route as WorkspaceInvestigationsRouteImport } from './routes/_workspace/investigations'
import { Route as WorkspaceReportsRouteImport } from './routes/_workspace/reports'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRouteRoute = WorkspaceRouteRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceAlertsRoute = WorkspaceAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceAssetsRoute = WorkspaceAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceCaseAnalysisRoute = WorkspaceCaseAnalysisRouteImport.update({
  id: '/case-analysis',
  path: '/case-analysis',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceDashboardRoute = WorkspaceDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceDatasetAnalysisRoute =
  WorkspaceDatasetAnalysisRouteImport.update({
    id: '/dataset-analysis',
    path: '/dataset-analysis',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceEvidenceRoute = WorkspaceEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceInvestigationsRoute = WorkspaceInvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceReportsRoute = WorkspaceReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof WorkspaceAlertsRoute
  '/assets': typeof WorkspaceAssetsRoute
  '/case-analysis': typeof WorkspaceCaseAnalysisRoute
  '/dashboard': typeof WorkspaceDashboardRoute
  '/dataset-analysis': typeof WorkspaceDatasetAnalysisRoute
  '/evidence': typeof WorkspaceEvidenceRoute
  '/investigations': typeof WorkspaceInvestigationsRoute
  '/reports': typeof WorkspaceReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof WorkspaceAlertsRoute
  '/assets': typeof WorkspaceAssetsRoute
  '/case-analysis': typeof WorkspaceCaseAnalysisRoute
  '/dashboard': typeof WorkspaceDashboardRoute
  '/dataset-analysis': typeof WorkspaceDatasetAnalysisRoute
  '/evidence': typeof WorkspaceEvidenceRoute
  '/investigations': typeof WorkspaceInvestigationsRoute
  '/reports': typeof WorkspaceReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_workspace/alerts': typeof WorkspaceAlertsRoute
  '/_workspace/assets': typeof WorkspaceAssetsRoute
  '/_workspace/case-analysis': typeof WorkspaceCaseAnalysisRoute
  '/_workspace/dashboard': typeof WorkspaceDashboardRoute
  '/_workspace/dataset-analysis': typeof WorkspaceDatasetAnalysisRoute
  '/_workspace/evidence': typeof WorkspaceEvidenceRoute
  '/_workspace/investigations': typeof WorkspaceInvestigationsRoute
  '/_workspace/reports': typeof WorkspaceReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alerts'
    | '/assets'
    | '/case-analysis'
    | '/dashboard'
    | '/dataset-analysis'
    | '/evidence'
    | '/investigations'
    | '/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/alerts'
    | '/assets'
    | '/case-analysis'
    | '/dashboard'
    | '/dataset-analysis'
    | '/evidence'
    | '/investigations'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/login'
    | '/_workspace/alerts'
    | '/_workspace/assets'
    | '/_workspace/case-analysis'
    | '/_workspace/dashboard'
    | '/_workspace/dataset-analysis'
    | '/_workspace/evidence'
    | '/_workspace/investigations'
    | '/_workspace/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRouteRoute: typeof WorkspaceRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/alerts': {
      id: '/_workspace/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof WorkspaceAlertsRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/assets': {
      id: '/_workspace/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof WorkspaceAssetsRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/case-analysis': {
      id: '/_workspace/case-analysis'
      path: '/case-analysis'
      fullPath: '/case-analysis'
      preLoaderRoute: typeof WorkspaceCaseAnalysisRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/dashboard': {
      id: '/_workspace/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof WorkspaceDashboardRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/dataset-analysis': {
      id: '/_workspace/dataset-analysis'
      path: '/dataset-analysis'
      fullPath: '/dataset-analysis'
      preLoaderRoute: typeof WorkspaceDatasetAnalysisRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/evidence': {
      id: '/_workspace/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof WorkspaceEvidenceRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/investigations': {
      id: '/_workspace/investigations'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof WorkspaceInvestigationsRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/reports': {
      id: '/_workspace/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof WorkspaceReportsRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
  }
}

interface WorkspaceRouteRouteChildren {
  WorkspaceAlertsRoute: typeof WorkspaceAlertsRoute
  WorkspaceAssetsRoute: typeof WorkspaceAssetsRoute
  WorkspaceCaseAnalysisRoute: typeof WorkspaceCaseAnalysisRoute
  WorkspaceDashboardRoute: typeof WorkspaceDashboardRoute
  WorkspaceDatasetAnalysisRoute: typeof WorkspaceDatasetAnalysisRoute
  WorkspaceEvidenceRoute: typeof WorkspaceEvidenceRoute
  WorkspaceInvestigationsRoute: typeof WorkspaceInvestigationsRoute
  WorkspaceReportsRoute: typeof WorkspaceReportsRoute
}

const WorkspaceRouteRouteChildren: WorkspaceRouteRouteChildren = {
  WorkspaceAlertsRoute: WorkspaceAlertsRoute,
  WorkspaceAssetsRoute: WorkspaceAssetsRoute,
  WorkspaceCaseAnalysisRoute: WorkspaceCaseAnalysisRoute,
  WorkspaceDashboardRoute: WorkspaceDashboardRoute,
  WorkspaceDatasetAnalysisRoute: WorkspaceDatasetAnalysisRoute,
  WorkspaceEvidenceRoute: WorkspaceEvidenceRoute,
  WorkspaceInvestigationsRoute: WorkspaceInvestigationsRoute,
  WorkspaceReportsRoute: WorkspaceReportsRoute,
}

const WorkspaceRouteRouteWithChildren = WorkspaceRouteRoute._addFileChildren(
  WorkspaceRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRouteRoute: WorkspaceRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
